### ISSUE TITLE
Remove runtime dependency on lein-doo

### ISSUE THREAD

**Issue by smee** [keechma/forms#2]
I think the lein-doo dependency is only needed at test time, not at runtime. 

The problem manifests itself in combination of figwheel 0.5.4-5 and keechma/forms:

In my project I'm using figwheel version 0.5.4-5, which has a new behaviour: If a request asks for the resource path '/' it looks for 'public/index.html' resources in the applications classpath. Since it currently finds the 'index.html' in lein-doo it never calls my own application handler, hence I never get the chance to create my page.

**Comment by smee** [comment]
Actually, the same problem occurs because there is a public/index.html in resources. Maybe these can be moved to a dedicates folder that is only included in a dev profile?

**Comment by retro** [comment]
@smee What is the easiest way to reproduce the error?

**Comment by smee** [comment]
That would be a project using the most recent figwheel and a ring handler that tries to generate 'index.html' dynamically. But I think this is no error in keechma/forms per se. Instead, the fact that there will be multiple 'public/index.html' files available in the classpath of downstream projects may lead to problems in these projects (like mine, for example). lein-doo and keechma/forms both have this file as part of their classpath, so which file gets read is pretty much depending on the order of entries in the classpath, i.e. non-deterministic.

**Comment by retro** [comment]
I've just pushed the new version that has no `public/index.html` file (it wasn't needed anyway). Please reopen this issue if you will still experience problems.
