### ISSUE TITLE
Transitive dependency issue with `lein-doo` in dependencies

### ISSUE THREAD

**Issue by smitch88** [keechma/forms#5]
#### Issue

First off, great form library. You saved me at least a couple weeks of work with this lib. I'm currently using it one of my projects and noticed that the built in figwheel server cannot server up the proper index.html due to a transitive dependency from `lein-doo`.

Here are 2 references:
##### Shows a discussion w/ someone specfically saying they also had the issue with forms lib
https://github.com/bhauman/lein-figwheel/issues/428

##### Shows an issue in the reagent-template build due to lein-doo in deps
https://github.com/reagent-project/reagent-template/issues/128

#### Solution

Remove `lein-doo` from project deps

**Comment by retro** [comment]
@smitch88 I've pushed a new version (0.1.3) which should fix this problem. Please reopen the issue if the problem persists

**Comment by smitch88** [comment]
Thank you for such a quick response. I was about to PR for you 👍  but you beat me to it. I had to update my lein to run your tests haha

Update: Works!
