### ISSUE TITLE
Is there a way to do validations where the validation depends on two form fields?

### ISSUE THREAD

**Issue by mynomoto** [keechma/forms#6]
Example: password and password confirmation being equal?

**Comment by retro** [comment]
@mynomoto Yes, check here https://github.com/retro/forms-validations/blob/master/src/forms_validation/validations.cljs#L15-L21 . You can see the demo in action here https://keechma.com/demos/forms/ and blog post about the motivation behind the library here https://medium.com/wdstack/inline-validation-in-forms-designing-the-experience-123fb34088ce
